Repository finnishtransportagency/viite, pull requests merged in 2018-03, with the labels that each got.

#15 Viite 1123 some calibration points not drawing correctly
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
Labels: merge_ready

#16 VIITE-1167 road address in URL opens wrong layer
  viite-UI/src/router.js
Labels: merge_ready

#26 Viite 1123 some calibration points not drawing correctly
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/CalibrationPointsUtils.scala
Labels: urgent

#22 Viite 1041 road addresses on suravage links are displayed
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
Labels: merge_ready

#30 VIITE-1198 Added fix for single link in road for tracks validation
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#35 VIITE-1206 Visualization of the Yhteenvetotaulukko
  viite-UI/src/less/site/project-change-table.less
  viite-UI/src/view/ProjectChangeTable.js
Labels: merge_ready

#37 VIITE-1213 Fix in new road parts re-reservation
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala
Labels: merge_ready, new_changes_after_original_reviews

#41 VIITE-1216_VIITE-1114 start date bug fix
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala
Labels: merge_ready

#45 VIITE-1224 Validation for missing tracks
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
Labels: merge_ready

#44 VIITE-1218 apply changes filter
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
Labels: merge_ready

#25 Viite 1139 oth integration api
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadAddressDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressesService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/FloatingChecker.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala
  src/main/scala/ScalatraBootstrap.scala
Labels: merge_ready

#42 Viite 1212 fuse road address history
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
Labels: merge_ready
