Repository finnishtransportagency/viite, pull requests merged in 2018-09, with the labels that each got.

#238 Viite 1477 adding a floating reason
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/SearchApi.scala
  digiroad2-oracle/src/main/resources/db/migration/V0_16__remove_constraint_ra_floating_is_boolean.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/FloatingCheckerSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressSplitMapperSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackSectionOrderSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/AssetDataImporterSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/GuestimateGeometryForMissingLinksSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala
Labels: merge_ready

#265 VIITE-1460 Show the roads does not work
  viite-UI/src/analytics.js
  viite-UI/src/application.js
  viite-UI/src/model/ApplicationModel.js
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/model/RoadCollection.js
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/model/SelectedProjectLink.js
  viite-UI/src/router.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/view/CoordinatesDisplay.js
  viite-UI/src/view/Layer.js
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/MapView.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectForm.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/ProjectLinkStyler.js
  viite-UI/src/view/RoadLayer3.js
  viite-UI/src/view/RoadLinkStyler.js
  viite-UI/src/view/Styler.js
  viite-UI/src/view/TileMapCollection.js
  viite-UI/src/view/TileMapSelector.js
Labels: merge_ready, new_changes_after_original_reviews

#270 Viite common history ids fixes
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/CommonHistoryFiller.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
Labels: DO NOT MERGE

#268 Viite 1515 link can not be selected and it is unseen when zooming
  digiroad2-oracle/src/main/resources/db/migration/V0_16__recreate_project_link_history.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/ProjectEditForm.js
Labels: merge_ready

#271 Viite 1516 duplicated road addresses
  digiroad2-oracle/src/main/resources/db/migration/V0_16__duplicated_road_address_constraint.sql
Labels: merge_ready

#273 Viite 1528 unable to choose adjacent unknown links while defloating
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
Labels: merge_before_1535, merge_ready

#274 VIITE-1170 fixing end dates for history links.
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_before_1535, merge_ready

#275 Viite 1502 fix unknown adjacency problems
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressFiller.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
Labels: merge_before_1535, merge_ready

#276 VIITE-1530 Group project link history by road number and road part
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
Labels: merge_before_1535, merge_ready

#277 Viite 1529 ui bugs after major refactoring
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  viite-UI/src/model/ApplicationModel.js
  viite-UI/src/model/RoadCollection.js
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/ProjectLinkLayer.js
Labels: merge_before_1535, new_changes_after_original_reviews

#280 VIITE-1171 - Adding history to unchanged addresses
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_before_1535, merge_ready

#210 Viite 1411 creation of corrective road address projects
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackSectionOrderSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/GuestimateGeometryForMissingLinksSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/ProjectChangeTable.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectForm.js
  viite-UI/src/view/SplitForm.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
  viite-UI/test/integration-tests/FloatingRoadAddressSpec.js
  viite-UI/test_data/RoadAddressProjectTestData.js
Labels: merge_before_1535, merge_ready

#288 VIITE-1461_part2_the_value_of_the_continuity-code_changes_in_view_mode
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/view/LinkPropertyForm.js
Labels: Merging, merge_ready

#301 clicking the map with one click clears selection in project and linkp…
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/ProjectLinkLayer.js
Labels: merge_ready
