Repository finnishtransportagency/viite, pull requests merged in 2018-11, with the labels that each got.

#336 VIITE-1373 - Nimityökalu: Vuosiluvun rajoitus alkupäivämäärässä / Name tool: restriction of the year of the start date
  viite-UI/src/model/RoadNameCollection.js
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: VIITE_OLD

#344 VIITE-1373 Start date validation
  viite-UI/src/model/RoadNameCollection.js
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: merge_ready

#355 Viite 1668 url search by linkid in suravage links does not work
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  viite-UI/src/router.js
  viite-UI/src/utils/zoom-levels.js
Labels: Roadway/Linear Location logic, merge_ready, new_changes_after_original_reviews

#346 Viite 1657 recalculation in two tracks does not adjust addr m values v3
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/view/ProjectEditForm.js
Labels: VIITE_OLD, merge_ready, new_changes_after_original_reviews

#350 Viite 1675 port 1657 to master
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/view/ProjectEditForm.js
Labels: Roadway/Linear Location logic, new_changes_after_original_reviews

#362 Viite 1657 non connectecd roads
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
Labels: VIITE_OLD, urgent

#351 VIITE-1373_removed_future_date_since_original_start_date
  viite-UI/src/utils/date-utils.js
  viite-UI/src/view/RoadNamingToolWindow.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: Roadway/Linear Location logic, merge_ready

#349 Viite 1672 wrong start date of project
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  viite-UI/src/utils/backend-utils.js
Labels: Roadway/Linear Location logic, merge_ready

#343 VIITE-1642-Implement road address search functionality in Viite UI
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  viite-UI/src/model/LocationSearch.js
  viite-UI/src/utils/backend-utils.js
Labels: new_changes_after_original_reviews

#363 Viite 1657 non connected roads master
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
Labels: Roadway/Linear Location logic, merge_ready, urgent

#364 Viite 1541 publishing the project
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-oracle/src/main/resources/db/migration/V0_10__changes_to_change_table_process.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/Sequences.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressSplitMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayFiller.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/RoundaboutSectionCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/Dummies.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ViiteTierekisteriClientSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectReservedPartDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayChangesDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadwayDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadwayFillerSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala
  viite-UI/src/application.js
  viite-UI/src/router.js
  viite-UI/src/utils/zoom-levels.js
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/MapView.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/RoadLayer.js
  viite-UI/src/view/ZoomBox.js
Labels: Roadway/Linear Location logic

#368 Viite 1657 direct creation fix to master
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackSectionOrderSpec.scala
Labels: Roadway/Linear Location logic, urgent
