Repository finnishtransportagency/viite, pull requests merged in 2018-12, with the labels that each got.

#370 VIITE-1708 - Added validation for AJR field when creating a new road address
  viite-UI/src/view/ProjectEditForm.js
Labels: merge_ready

#369 VIITE-1671 - Added message at the bottom of the name tool modal
  viite-UI/src/less/site/modals.less
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: merge_ready

#373 VIITE-1671 VIITE_OLD Added message at the bottom of the name tool modal
  viite-UI/src/less/site/modals.less
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: VIITE_OLD

#376 VIITE-1708 - Added validation for AJR field when creating a new road address
  viite-UI/src/view/ProjectEditForm.js
Labels: VIITE_OLD

#377 Viite 1541 fixes
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala
Labels: merge_ready

#375 VIITE-1677 VIITE-1707 master road names fixes
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/ProjectEditForm.js
Labels: Roadway/Linear Location logic, new_changes_after_original_reviews

#383 Viite 1725 corrections for visualization
  viite-UI/src/view/ProjectLinkStyler.js
  viite-UI/src/view/RoadLinkStyler.js
Labels: new_changes_after_original_reviews

#379 Viite 1239 splitting suravage links
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressFiller.scala
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/SplitForm.js
  viite-UI/test/integration-tests/SplittingRoadAddressSpec.js
Labels: merge_ready

#380 VIITE-1721 and VIITE-1051-road name when changing road number & Expire road names when roadway changes have Termination change type
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNameDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_ready

#395 VIITE-1725 Added default lineCap rule. Upon selection of type 3 or 5 the black o…
  viite-UI/src/utils/StyleRule.js
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/RoadLinkStyler.js
Labels: new_changes_after_original_reviews
