Repository finnishtransportagency/viite, pull requests merged in 2018-04, with the labels that each got.

#49 Viite-1226
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
Labels: merge_ready

#50 Viite 1227 false jatkuvuus validation message
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadNetworkService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  viite-UI/src/model/ProjectCollection.js
Labels: merge_ready

#57 Viite 1237 wrong change table recalculation in reverse
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: urgent

#59 VIITE-1243 Fix in road length in road part reservation where the leng…
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_ready

#56 Viite 1228 and VIITE-1234 wrong loop directions and allow discontinuity drop down on numbering
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/PointSpec.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackSectionOrderSpec.scala
  viite-UI/src/view/ProjectEditForm.js
Labels: merge_ready

#51 Viite-1229
  digiroad2-oracle/sql/insert_road_address_data.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
Labels: new_review_required

#62 Viite 1242 diferent road type in same link
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/model/SelectedProjectLink.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectForm.js
  viite-UI/src/view/ProjectLinkLayer.js
Labels: merge_ready

#64 Viite 1247 the user can not open project
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadNameService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectLinkNameDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNameDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectAddressLink.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLink.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadNameServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/model/RoadNameCollection.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/utils/date-utils.js
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/RoadNamingToolWindow.js
  viite-UI/src/view/WorkListView.js
Labels: merge_ready

#66 VIITE-1263 apply changes fix
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
Labels: merge_ready

#67 Viite 1246 reversing direction with user given end addr m value breaks road lengths
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionMValueCalculator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_ready

#69 VIITE-1269 roundabout floating transfer
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
Labels: merge_ready

#70 VIITE-1284 Refactored and fixed adjacency for selected link in group
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/view/LinkPropertyLayer.js
Labels: merge_ready

#71 Viite 1268 4 road addresses are floatings in qa
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/AssetDataImporterSpec.scala
Labels: merge_ready

#72 VIITE-1285- Käyttäjä ei voi vierittää karttaa valitessaan tuntemattomia
  viite-UI/src/view/LinkPropertyLayer.js
Labels: merge_ready

#74 Viite 1289 when user redirect new road, viite changes continuity code of other road
  conf/dev/keys.properties
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_ready

#77 VIITE 1288 Viite changes data of unselected link
  viite-UI/src/view/ProjectLinkLayer.js
Labels: merge_ready
