Repository finnishtransportagency/viite, pull requests merged in 2018-08, with the labels that each got.

#236 VIITE-1485_user_cannot_make_new_road_address_reservations_after_removing_existing_reservation_from_project
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  viite-UI/src/view/ProjectForm.js
Labels: merge_ready

#233 Viite 1483 form shows geometry source of link
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/SplitForm.js
Labels: merge_ready

#234 Viite 1377 apply changes with history
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
Labels: merge_ready

#242 Viite 1473 modified by field
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-oracle/src/main/resources/db/migration/V0_15__AddModifiedBy2RoadaddressTable.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadNetworkServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala
Labels: Merging

#241 Viite 1494 user cannot deselect floatings and the form is not updated
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/LinkPropertyLayer.js
Labels: Merging

#240 VIITE-1491 changed coefficient logic in floating transfer
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/FloatingChecker.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
  viite-UI/src/model/SelectedLinkProperty.js
Labels: merge_ready

#249 Viite 1503 address gap on transfer
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala
Labels: merge_ready

#246 Viite 1502 find adjacent unknown links sometimes does not return adjacents
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
Labels: Merging, merge_ready

#250 Viite 1510 the letters of the adjacent floatings are behind of the yellow line on the map
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
Labels: Merging

#254 Viite 1505 creating two road address segments at the same place
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/view/LinkPropertyForm.js
Labels: merge_ready

#257 Viite 1507 2 segments on top of each other + wrong growing direction when made not floating
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala
Labels: merge_ready
