Repository finnishtransportagency/viite, pull requests merged in 2018-05, with the labels that each got.

#80 VIITE-1309 Logs accessible to monitoring
  config/deploy.rb
Labels: urgent

#78 Viite 1281 monitoring
  project/build.scala
  src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
  start.sh
Labels: merge_ready

#93 Viite 1299 bugs in road name tool
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: merge_ready

#91 VIITE-1327 Ignoring terminated part in specific cases
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
Labels: merge_ready

#90 VIITE-1310 setting black underline to all Municipality Street Roads
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
Labels: merge_ready

#96 Viite 1242 road types stay same in road address change v2
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/CommonHistoryFiller.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/CalibrationPointsUtils.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
Labels: merge_ready

#98 VIITE-1329 - Bug fix on reserved road parts after transfer
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: DO NOT MERGE

#113 VIITE-1342 Project calculator gives wrong road address measures
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
Labels: merge_ready

#109 Viite 1336 roadnames table gets valid duplicate roadnames for same roadnumber
  digiroad2-oracle/src/main/resources/db/migration/V0_8__create unique_constraint_project_link_name.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_ready

#104 Viite 1316 error in viite status adding to viite
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: Merging, merge_ready

#108 VIITE-1242
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: Merging, merge_ready

#118 VIITE-1350 fixing suravage links to UI
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/ProjectLinkLayer.js
Labels: Merging

#128 VIITE-1238 Move the change table only from title bar
  viite-UI/src/view/ProjectChangeTable.js
Labels: merge_ready

#129 VIITE-1315 Clears text inputs after successful road reservation
  viite-UI/src/view/ProjectForm.js
Labels: merge_ready
