Repository finnishtransportagency/viite, pull requests merged in 2018-07, with the labels that each got.

#189 Viite 1429 changing ennallaan ordering validation
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#192 Viite 1401 error in removed end of road parts
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#197 VIITE-1431 cancel changes should clear selected links
  viite-UI/src/view/ProjectEditForm.js
Labels: merge_ready

#194 Viite 1398 removal empty error
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  viite-UI/src/modalconfirm/ModalConfirm.js
  viite-UI/src/view/ProjectEditForm.js
Labels: merge_ready

#202 Viite 1434 error in let values for track 1 and 2 in terminantion && VIITE-1442 Change name for Käännä kasvusuunta -button / Muuta Käännä kasvusuunta -painikkeen nimi
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
Labels: merge_ready

#199 Viite 1433 prioritize unchanged ordering errors in project validator
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#208 Viite 1444 ennallaan validation error
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#203 VIITE-1445, VIITE-1446 end of road in middle of road part
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#211 VIITE-1439 Remove OTH-specific code part 2
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/DigiroadEventBus.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
  digiroad2-oracle/src/main/resources/db/migration/V0_12__drop_oth_tables.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkServiceDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
  viite-UI/src/analytics.js
  viite-UI/src/assetgrouping/asset-grouping.js
  viite-UI/src/model/ApplicationModel.js
  viite-UI/src/router.js
  viite-UI/src/view/LinkPropertyMassUpdateDialog.js
  viite-UI/src/view/RoadLayer.js
  viite-UI/src/view/navigationpanel/ActionPanelBoxes.js
  viite-UI/src/view/navigationpanel/LayerSelectBox.js
  viite-UI/test/integration-tests.html
  viite-UI/tmpl/index.html
Labels: merge_ready, new_changes_after_original_reviews

#215 VIITE-1314 change popup text in save and editing roadname cases
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: merge_ready

#218 VIITE-1457 Fixed connectedDiscontinuousLink validation
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#225 VIITE-1307_gray_background_for_roadtype_5_on_the_map
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
Labels: new_changes_after_original_reviews

#228 Viite 1468 and 1469 floating fixe
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitioner.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/view/LinkPropertyForm.js
Labels: new_changes_after_original_reviews

#230 Viite 1475 change logic of lrm position checker batch
  digiroad2-oracle/src/main/resources/db/migration/V0_13__create_unique_constraint_road_nework_errors.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadNetworkDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
Labels: new_changes_after_original_reviews

#235 VIITE-1488 added function where it is possible to start the transfer …
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/LinkPropertyLayer.js
Labels: merge_ready

#220 Viite 1447 missing terminated row from change table
  digiroad2-oracle/src/main/resources/db/migration/V0_13__create_project_link_calibration_point_source.sql
  digiroad2-oracle/src/main/resources/db/migration/V0_14__create_unique_constraint_road_nework_errors.sql
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/RoundaboutSectionCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/CalibrationPointsUtils.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/CommonHistoryFillerSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala
Labels: merge_ready

#224 Viite 1461 the value of the continuity code changes in view mode
  viite-UI/src/model/SelectedLinkProperty.js
Labels: merge_ready
