Repository finnishtransportagency/viite, pull requests merged in 2018-06, with the labels that each got.

#137 VIITE-1355 Clean direction icons each time we switch the project link…
  viite-UI/src/view/ProjectLinkLayer.js
Labels: merge_ready

#133 VIITE-1366
  viite-UI/src/utils/zoom-levels.js
  viite-UI/src/view/LinkPropertyLayer.js
Labels: merge_ready

#142 Viite 1343 save calibration points initial import
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/RoadAddressImporter.scala
Labels: merge_ready

#147 Viite 1370 Project name from bits to char
  digiroad2-oracle/src/main/resources/db/migration/V0_9__road_address_name_limit_to_charbased.sql
Labels: merge_ready

#131 VIITE-1361
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: new_changes_after_original_reviews

#146 VIITE-1367 Opening a project takes very long time
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: merge_ready

#127 Viite 1340 check what happen in road address change when road links has been changed
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectLinkPartitioner.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionMValueCalculator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/ProjectForm.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: Merging, merge_ready

#144 Viite 1369 change apply changes batch logic
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressMapper.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala
Labels: merge_ready

#138 Viite 1262 show only own projects button to the project list
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  viite-UI/src/less/core/buttons.less
  viite-UI/src/less/site/action-panel.less
  viite-UI/src/less/site/global.less
  viite-UI/src/model/ApplicationModel.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/utils/eventbus.js
  viite-UI/src/view/navigationpanel/ActionPanelBoxes.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
  viite-UI/src/view/navigationpanel/RoadLinkBox.js
Labels: merge_ready, need_changes

#155 Viite 1368 1316 fixing road names are not obligatory if road number is above 70000
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
Labels: merge_ready

#152 Viite 1377 splitted link does not find geometry
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
Labels: merge_ready

#156 VIITE-1262 Project list is now filtered also after sorting
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: merge_ready

#158 Viite-1306 Add roadtype 3 ja 5 to legend
  viite-UI/src/less/site/action-panel.less
  viite-UI/src/view/navigationpanel/RoadLinkBox.js
Labels: merge_ready

#160 Viite 1373 name tool restriction of the year of the start date
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: merge_ready

#141 Viite 1344 reverting previous changes
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
  viite-UI/src/model/RoadCollection.js
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/LinkPropertyLayer.js
Labels: merge_ready

#161 Viite 1393 loggin when vvh is not responding
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
Labels: new_changes_after_original_reviews

#166 VIITE-1259 displaying old projects on the project list
  viite-UI/src/less/core/forms.less
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: merge_ready

#167 VIITE-1400 cleaning the selection of linkPropertyLayer when changing …
  viite-UI/src/model/ApplicationModel.js
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/view/ProjectForm.js
Labels: merge_ready

#168 VIITE-1360 Remove municipality restrictions from code
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
Labels: merge_ready

#165 VIITE-1399 reservation of road parts fails
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
Labels: new_changes_after_original_reviews

#171 VIITE-1405 Create_date in project list instead of project start_date
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: merge_ready

#170 Viite 1398 sending to tr status for project
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDaoSpec.scala
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: merge_ready

#173 Viite 1404 changes for zooming and link selecting
  viite-UI/src/application.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/view/MapView.js
  viite-UI/src/view/ProjectLinkLayer.js
Labels: need_changes

#178 VIITE-1374 Incorrect start date gets name tool stuck
  viite-UI/src/view/RoadNamingToolWindow.js
Labels: merge_ready

#179 Viite 1311 show roads checkbox
  viite-UI/src/less/site/map-plugins.less
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/TileMapSelector.js
Labels: merge_ready

#183 Viite 1391 1392 project validator refactoring
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/CommonHistoryFiller.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultSectionCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DefaultTrackCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DiscontinuityTrackCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/LinkStatusChangeTrackCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/RoadAddressSectionCalculatorStrategy.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
  viite-UI/src/application.js
  viite-UI/src/less/site/map-plugins.less
  viite-UI/src/map/ProjectLinkMarker.js
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/model/RoadCollection.js
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/src/view/MapView.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectForm.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/RoadLayer3.js
  viite-UI/src/view/RoadNamingToolWindow.js
  viite-UI/src/view/Styler.js
  viite-UI/src/view/TileMapSelector.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
  viite-UI/test/TestHelpers.js
  viite-UI/test/integration-tests/FloatingRoadAddressSpec.js
  viite-UI/test/integration-tests/RoadAddressProjectSpec.js
  viite-UI/test_data/RoadLinkTestData.js
Labels: merge_ready

#187 VIITE-1421_ajr_1_2_cases_for_1394
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: merge_ready

#188 VIITE-1414 Change warning message to 20%.
  viite-UI/src/model/ProjectCollection.js
Labels: merge_ready

#190 Viite 1407 new headers for floatings and unknowns
  viite-UI/src/less/core/forms.less
  viite-UI/src/less/site/asset-form.less
  viite-UI/src/model/SelectedLinkProperty.js
  viite-UI/src/utils/LinkValues.js
  viite-UI/src/utils/backend-utils.js
  viite-UI/src/view/LinkPropertyForm.js
  viite-UI/src/view/LinkPropertyLayer.js
  viite-UI/test/integration-tests/FloatingRoadAddressSpec.js
Labels: merge_ready

#184 VIITE-1415
  viite-UI/src/view/TileMapSelector.js
  viite-UI/src/view/navigationpanel/ProjectListModel.js
Labels: merge_ready

#185 VIITE-1416 Fixes to UI
  viite-UI/src/less/site/asset-form.less
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/ProjectChangeTable.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectForm.js
  viite-UI/src/view/ProjectLinkLayer.js
  viite-UI/src/view/SplitForm.js
Labels: merge_ready

#186 VIITE-1410 UUSI action with invalid road number has unwanted behavior
  viite-UI/src/model/ProjectCollection.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/ProjectLinkLayer.js
Labels: merge_ready, new_changes_after_original_reviews
