Repository finnishtransportagency/viite, pull requests merged in 2019-02, with the labels that each got.

#438 VIITE-1775 Fixed missing reversed roads in reversing project
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
Labels: new_changes_after_original_reviews

#453 Viite 1771 project changes validation fixes
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: new_changes_after_original_reviews

#460 VIITE-1806 Form inputs disabled if project status is not incomplete.
  viite-UI/src/view/FormCommon.js
  viite-UI/src/view/ProjectEditForm.js
  viite-UI/src/view/SplitForm.js
Labels: new_changes_after_original_reviews

#461 VIITE-1807 fix and revert some wrong code
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectValidatorSpec.scala
Labels: DO NOT MERGE

#470 Viite 1805 bug in automatic reversion v2
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/LinearLocationDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadwayDAO.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/TrackCalculatorStrategy.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
Labels: new_changes_after_original_reviews

#476 VIITE-1812 minor discontinuities on roundabout
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/strategy/DiscontinuityTrackCalculatorStrategy.scala
Labels: merge_ready

#483 VIITE-1835 infinite recursion
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadwayAddressMapper.scala
Labels: merge_ready

#488 Viite 1839 integration api zero links
  digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
Labels: urgent
